### ISSUE TITLE
Couldn't include a single file

### ISSUE THREAD

**Issue by shlevy** [numtide/treefmt#102]
This worked:

```toml
[formatter.cabal]
command = "cabal-fmt"
options = [
  "--inplace"
]
includes = ["*.cabal"]
```

This didn't

```toml
[formatter.cabal]
command = "cabal-fmt"
options = [
  "--inplace"
]
includes = ["scarf.cabal"]
```

though the debug output did say "1 literals" for cabal-fmt.
