### ISSUE TITLE
Add support for linters

### ISSUE THREAD

**Issue by zimbatm** [numtide/treefmt#11]
Unlike formatters, multiple linters can be executed for a single file. Linters sometimes also write back fixes to the file.

The config format has rooms for a `[linters.<name>]` section.

This needs to be specced-out a bit more.

**Comment by zimbatm** [comment]
See also https://github.com/reviewdog/reviewdog

**Comment by 9999years** [comment]
I would like this to work around https://github.com/astral-sh/ruff/issues/8232 by running `ruff check --fix && ruff format`.

**Comment by zimbatm** [comment]
Something like this should work:
```toml
[formatter.ruff]
command = "sh"
options = ["-c", "ruff check \"$@\" && ruff format \"$@\"", "--"]
includes = ["*.py", "*.pyi"]
```
