### ISSUE TITLE
Formatters are invoked even with 0 files

### ISSUE THREAD

**Issue by zimbatm** [numtide/treefmt#141]
**Describe the bug**

Treefmt calls the formatter, even if there are no files to format.

I noticed that when trying to use shellcheck, who fails where there are 0 arguments passed to it.

**To Reproduce**

Add this to your `treefmt.toml`:
```toml
[formatter.shell]
command = "/bin/sh"
options = [
    "-c",
    """
set -euo pipefail

# First shellcheck
shellcheck "$@"
# Then format
shfmt -i 2 -s -w "$@"
    """
]
includes = ["*.sh"]
excludes = []
```

**Expected behavior**

Not call the script when there are no files to format.
