### ISSUE TITLE
eval cache doesn't extend to shell scripts

### ISSUE THREAD

**Issue by zimbatm** [numtide/treefmt#149]
**Describe the bug**

Recently I encountered an issue where shellcheck got upgraded (through a nixpkgs bump), but treefmt's eval cache didn't get invalidated.

**To Reproduce**

Treefmt tracks the mtime of the program being invoked. But if the program is a shell wrapper then it doesn't work anymore. treefmt is not able to find out that shellcheck is being used in something like this:
```toml
[formatter.shell]
command = "sh"
options = [
    "-eucx",
    """
# This is a bug in treefmt, the script should not be called without arguments
if [[ $# -le 0 ]]; then exit 0; fi
# First shellcheck
shellcheck "$@"
# Then format
shfmt -i 2 -s -w "$@"
    """
]
includes = ["*.sh"]
excludes = []
```

**Expected behavior**

The cache needs to be precise, otherwise, it introduces uncertainty and wastes the user's time. This is a general problem as any code formatter can invoke arbitrary programs and files.

On possible solution would be to allow the user to manually list the dependencies and collect them.

Eg:
```
[formatter.shell]
command = "sh"
options = [
    "-eucx",
    """
shellcheck "$@"
shfmt -i 2 -s -w "$@"
    """
]
includes = ["*.sh"]
excludes = []
dependent_programs = ["shellcheck", "shfmt"]
```

**System information**

**Additional context**
