### ISSUE TITLE
Parse hidden files

### ISSUE THREAD

**Issue by loicreynier** [numtide/treefmt#153]
I am not sure if this is intended or not, but hidden files are not formatted while running `treefmt` in the project root directory. I do not see why hidden files, which are generally configuration files should not be formatted.

**Describe the solution you'd like**

I would like to have hidden files formatted while running `treefmt` in the project root directory.

**Describe alternatives you've considered**

Currently hidden files can be formatted by passing them as command line arguments as in  

```shell
treefmt .pre-commit-config.yaml
```

**Comment by zimbatm** [comment]
It's something that comes default with the [ignore](https://github.com/BurntSushi/ripgrep/tree/master/crates/ignore) crate. It's quite convenient as some of the hidden folders like `.git` wouldn't make sense to traverse.

I think this should stay the default but still look at hidden files IFF they are listed explicitly in the config.

**Comment by loicreynier** [comment]
I agree with you, I did not think about the hidden directories and yes a better alternative is having the following configuration file:

```toml
[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = [
    ".pre-commit-config.yaml",
    "*.yaml",
]
```
