### ISSUE TITLE
what does "One or more formatters are missing" mean? 

### ISSUE THREAD

**Issue by MangoIV** [numtide/treefmt#286]
**Describe the bug**

I'm trying to run selected formatters of the ones declared in my treefmt.toml, I get "One or more formatters missing" 

**To Reproduce**

following `treefmt.toml`
```toml
[formatter.nix]
command = "nixpkgs-fmt"
includes = ["*.nix"]
excludes = [ "nix/sources.nix"] # managed by niv. 

[formatter.cabal-fmt]
command = "cabal-fmt"
options = [ "--inplace" ]
includes = [ "*.cabal" ]
excludes = [ "dist-newstyle/" ]

[formatter.ormolu]
command = "ormolu"
includes = ["*.hs"]
excludes = [ "dist*" ]
options = [
  "--mode", "inplace", 
  "--check-idempotence",
]

[formatter.hlint]
command = "hlint"
includes = ["*.hs"]
excludes = [ "dist*" ]

[formatter.shellcheck]
command = "shellcheck"
includes = ["*.sh"]
excludes = []
```

run `treefmt -v -f cabal-fmt`, get `[ERROR] One or more formatters are missing` what does this mean? I want to only run `cabal-fmt`; there's a formatter in the `toml` that is called that and `cabal-fmt` *is* available. 

**Expected behavior**

it runs only the `cabal-fmt` formatter

**System information**

treefmt version 0.6.1, nixos nixpkgs unstable

**Additional context**
n/a
