### ISSUE TITLE
feat: add dart format support

### ISSUE THREAD

**Issue by JakobLichterfeld** [numtide/treefmt#410]
As a user I do want to lint my dart code with treefmt multiplexer as well.

imo [`dart format`](https://dart.dev/tools/dart-format) follows the [formatter-spec](https://treefmt.com/formatter-spec)

Using the `treefmt.toml` configuration:

```toml
[formatter.dart]
command = "dart format"
options = []
includes = [ "*.dart" ]
```

results in `treefmt: error: formatter command not found in PATH: failed to initialise formatter: dart` even if dart format is present in `$PATH`

Happy to do a PR once pushed in the right direction.
