### ISSUE TITLE
Disable linters rather than enable linters in golangci-lint

### ISSUE THREAD

**Issue by Mic92** [numtide/treefmt#484]
I found there are still quite a few useful lints that also prevented actual bugs in niks3:

I saved this as `golangci2.yml` to incrementally enable more linters in https://github.com/numtide/treefmt/pull/483

```
linters:
    enable-all: true
    disable:
        - depguard
        - execinquery
        - exhaustruct
        - exportloopref
        - funlen
        - godox
        - gomnd
        - mnd
        - varnamelen
        - forbidigo
        - gocognit
        - gocyclo
        - cyclop
        - err113
        - maintidx
        # would be nice to have but too many tests depend on environment variables, which is not allowed for t.Parallel()
        - paralleltest
```

and running:

```
golangci-lint run --config golangci2.yml
```
