### ISSUE TITLE
buf format fails with too many args received

### ISSUE THREAD

**Issue by drew-dirac** [numtide/treefmt#587]
**Describe the bug**

When I enable the buf formatter, I get the following error:
```
ERRO formatter | buf: failed to apply with options '[format -w]': exit status 1

Usage:
  buf format <source> [flags]

Flags:
      --config string          The buf.yaml file or data to use for configuration
  -d, --diff                   Display diffs instead of rewriting files
      --disable-symlinks       Do not follow symlinks when reading sources or configuration from the local filesystem
                               By default, symlinks are followed in this CLI, but never followed on the Buf Schema Registry
      --error-format string    The format for build errors printed to stderr. Must be one of [text,json,msvs,junit,github-actions] (default "text")
      --exclude-path strings   Exclude specific files or directories, e.g. "proto/a/a.proto", "proto/a"
                               If specified multiple times, the union is taken
      --exit-code              Exit with a non-zero exit code if files were not already formatted
  -h, --help                   help for format
  -o, --output string          The output location for the formatted files. Must be one of format [dir,protofile]. If omitted, the result is written to stdout (default "-")
      --path strings           Limit to specific files or directories, e.g. "proto/a/a.proto", "proto/a"
                               If specified multiple times, the union is taken
  -w, --write                  Rewrite files in-place

Global Flags:
      --debug               Turn on debug logging
      --log-format string   The log format [text,color,json] (default "color")
      --timeout duration    The duration until timing out, setting it to zero means no timeout (default 2m0s)

accepts at most 1 arg(s), received 59
```

**To Reproduce**

1. Enable `buf` as a formatter
2. Attempt to have more than one file formatted

**Expected behavior**

`buf` should be called on each file, one at a time to comply with the usage pattern they document.

**System information**

Using `treefmt-nix` on NixOS unstable

**Additional context**

Below is the `buf.yaml` used:
```yaml
version: v2
modules:
  - path: protos
# name: buf.build/diracinc/protos
deps:
  - buf.build/googleapis/googleapis
  - buf.build/grpc-ecosystem/grpc-gateway
lint:
  use:
    - STANDARD
breaking:
  use:
    - WIRE_JSON
    - WIRE
  except:
    - FIELD_NO_DELETE_UNLESS_NAME_RESERVED
    - ENUM_VALUE_NO_DELETE_UNLESS_NAME_RESERVED
  ignore_unstable_packages: true
  disable_builtin: false
```
