### ISSUE TITLE
Add --pre-commit mode

### ISSUE THREAD

**Issue by zimbatm** [numtide/treefmt#78]
Some developers like to invoke the formatters just before committing the code.

When invoked, it should only format the code that has been staged for the commit and not touch the rest.

This can be done like this: https://stackoverflow.com/a/26911078
And also probably check for unresolved merge commits before and abort if that's the case.

**Comment by ocharles** [comment]
I've ended up using `pre-commit` with this:

```yaml
repos:
  - repo: local
    hooks:
      - id: treefmt
        name: treefmt
        entry: treefmt
        language: system
        always_run: true
```

Seems to work well!

**Comment by loicreynier** [comment]
A `.pre-commit-hooks.yaml` file could also be added to this repository such as 

```yaml
- id: treefmt
  name: treefmt
  description: Format code with treefmt
  entry: treefmt
  language: rust
  minimum_pre_commit_version: 1.18.1
```

so that `pre-commit` could download and install (with Cargo and from crates) `treefmt` with

```yaml
repos:
  - repo: https://github.com/numtide/treefmt
    rev: master
    hooks:
      - id: treefmt
```
